/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Citizen;

import Business.EcoSystem;
import Citizen.Citizen;
import business.Area.Area;
import business.City.City;
import business.house.House;
import business.streetMap.Plot;
import business.streetMap.Street;
import businessLogic.formValidation.AlphabeticalDocumentFilter;
import businessLogic.formValidation.FormValidator;
import businessLogic.formValidation.NumericDocumentFilter;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.PlainDocument;
/**
 *
 * @author Aks
 */
public class RegisterCitizenJPanel extends javax.swing.JPanel {
    FormValidator formValidator;
    JPanel userPanel;
    EcoSystem eco;
    int errorCount;
    /**
     * Creates new form RegisterCitizenJPanel
     */
    public RegisterCitizenJPanel(EcoSystem es, JPanel userAreaPanel) {
       initComponents();
        eco = es;
        userPanel = userAreaPanel;
        formValidator = new FormValidator();
        setupDocumentFilter();
        loadCombos();
    }

    public void loadCombos() {
        cityCombo.removeAllItems();
        areaCombo.removeAllItems();
        streetCombo.removeAllItems();
        plotCombo.removeAllItems();
        aptCombo.removeAllItems();
        for (City city : eco.getCityList()) {
            cityCombo.addItem(city);
        }

    }

    public void setupDocumentFilter() {
        PlainDocument nameDoc = (PlainDocument) firstNameField.getDocument();
        nameDoc.setDocumentFilter(new AlphabeticalDocumentFilter());

        PlainDocument lastNameDoc = (PlainDocument) lastNameField.getDocument();
        lastNameDoc.setDocumentFilter(new AlphabeticalDocumentFilter());

        PlainDocument areaDoc = (PlainDocument) areaCodeField.getDocument();
        areaDoc.setDocumentFilter(new NumericDocumentFilter());

        PlainDocument phoneDoc = (PlainDocument) numberField.getDocument();
        phoneDoc.setDocumentFilter(new NumericDocumentFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        areaCodeField = new javax.swing.JTextField();
        numberField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        firstNameError = new javax.swing.JLabel();
        middleNameError = new javax.swing.JLabel();
        lastNameError = new javax.swing.JLabel();
        dobError = new javax.swing.JLabel();
        stAddressError = new javax.swing.JLabel();
        zipError = new javax.swing.JLabel();
        townError = new javax.swing.JLabel();
        occupationError = new javax.swing.JLabel();
        emailAddressError = new javax.swing.JLabel();
        phoneNumberError = new javax.swing.JLabel();
        commonErrorLabel = new javax.swing.JLabel();
        dobField = new javax.swing.JTextField();
        areaCombo = new javax.swing.JComboBox();
        streetCombo = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        plotCombo = new javax.swing.JComboBox();
        aptCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cityCombo = new javax.swing.JComboBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 51, 0));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Create Person");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("FirstName");

        firstNameField.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        firstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFieldFocusLost(evt);
            }
        });
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Last Name");

        lastNameField.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        lastNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFieldFocusLost(evt);
            }
        });
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Date of Birth");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Street");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Area");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Email Address");

        emailField.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 153));
        jLabel11.setText("Phone Number");

        areaCodeField.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        areaCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaCodeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaCodeFieldFocusLost(evt);
            }
        });

        numberField.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        numberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFieldFocusLost(evt);
            }
        });
        numberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Area Code");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 153));
        jLabel13.setText("Number");

        createButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        createButton.setForeground(new java.awt.Color(0, 102, 153));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        firstNameError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        firstNameError.setForeground(new java.awt.Color(255, 0, 0));

        middleNameError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        middleNameError.setForeground(new java.awt.Color(255, 0, 0));

        lastNameError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        lastNameError.setForeground(new java.awt.Color(255, 0, 0));

        dobError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        dobError.setForeground(new java.awt.Color(255, 0, 0));

        stAddressError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        stAddressError.setForeground(new java.awt.Color(255, 0, 0));

        zipError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        zipError.setForeground(new java.awt.Color(255, 0, 0));

        townError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        townError.setForeground(new java.awt.Color(255, 0, 0));

        occupationError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        occupationError.setForeground(new java.awt.Color(255, 0, 0));

        emailAddressError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailAddressError.setForeground(new java.awt.Color(255, 0, 0));

        phoneNumberError.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        phoneNumberError.setForeground(new java.awt.Color(255, 0, 0));

        commonErrorLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        commonErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        commonErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dobField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dobField.setForeground(new java.awt.Color(0, 102, 153));
        dobField.setText("mm/dd/yyyy");
        dobField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dobFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobFieldFocusLost(evt);
            }
        });
        dobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobFieldActionPerformed(evt);
            }
        });

        areaCombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        areaCombo.setForeground(new java.awt.Color(0, 102, 153));
        areaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        areaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboActionPerformed(evt);
            }
        });

        streetCombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        streetCombo.setForeground(new java.awt.Color(0, 102, 153));
        streetCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        streetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetComboActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Plot Number");

        plotCombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        plotCombo.setForeground(new java.awt.Color(0, 102, 153));
        plotCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        plotCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotComboActionPerformed(evt);
            }
        });

        aptCombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        aptCombo.setForeground(new java.awt.Color(0, 102, 153));
        aptCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        aptCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Apt. Number");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("City");

        cityCombo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cityCombo.setForeground(new java.awt.Color(0, 102, 153));
        cityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plotCombo, 0, 176, Short.MAX_VALUE)
                            .addComponent(areaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aptCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(streetCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(75, 75, 75)
                        .addComponent(cityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stAddressError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(zipError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(townError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(occupationError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(middleNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(emailAddressError, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(dobError, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(phoneNumberError, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(commonErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lastNameError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(middleNameError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(dobError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(phoneNumberError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(commonErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(areaCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stAddressError)
                                .addGap(63, 63, 63)
                                .addComponent(zipError)
                                .addGap(13, 13, 13)
                                .addComponent(townError)
                                .addGap(10, 10, 10)
                                .addComponent(occupationError)
                                .addGap(104, 104, 104)
                                .addComponent(emailAddressError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(areaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(streetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(plotCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(58, 58, 58)
                .addComponent(createButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusGained
        firstNameError.setText("");
        firstNameField.setBackground(Color.white);
        if (errorCount == 0) {
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_firstNameFieldFocusGained

    private void firstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFieldFocusLost

        if (formValidator.verifyStringInput(firstNameField.getText())) {
            if (formValidator.isAlphabetical(firstNameField.getText())) {
                if ((firstNameError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        firstNameError.setText("Please Enter a valid First Name");
        errorCount++;
        firstNameField.setBackground(Color.pink);
        createButton.setEnabled(false);
    }//GEN-LAST:event_firstNameFieldFocusLost

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusGained
        lastNameError.setText("");
        lastNameField.setBackground(Color.white);
        if (errorCount == 0) {
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_lastNameFieldFocusGained

    private void lastNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFieldFocusLost
        if (formValidator.verifyStringInput(lastNameField.getText())) {
            if (formValidator.isAlphabetical(lastNameField.getText())) {
                if ((lastNameError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        lastNameError.setText("Please Enter a valid last Name");
        errorCount++;
        lastNameField.setBackground(Color.pink);
        createButton.setEnabled(false);
    }//GEN-LAST:event_lastNameFieldFocusLost

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        emailAddressError.setText("");
        emailField.setBackground(Color.white);
        if (errorCount == 0) {
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        if (formValidator.verifyStringInput(emailField.getText())) {
            if (formValidator.verifyEmailAddress(emailField.getText())) {
                if ((emailAddressError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        emailAddressError.setText("Enter a valid Email ID(eg. xyz@abc.com)");
        errorCount++;
        emailField.setBackground(Color.pink);
        createButton.setEnabled(false);
    }//GEN-LAST:event_emailFieldFocusLost

    private void areaCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaCodeFieldFocusGained
        phoneNumberError.setText("");
        areaCodeField.setBackground(Color.white);
        numberField.setEditable(true);
        if (errorCount == 0) {
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_areaCodeFieldFocusGained

    private void areaCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaCodeFieldFocusLost
        boolean validationResult = formValidator.verifyStringInput(areaCodeField.getText());
        if (validationResult) {
            if (formValidator.verifyAreaCode(areaCodeField.getText())) {
                if ((phoneNumberError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        phoneNumberError.setText("Please Enter  a valid 3-digit Area Code");
        areaCodeField.setBackground(Color.pink);
        numberField.setEditable(false);
        errorCount++;
        createButton.setEnabled(false);
    }//GEN-LAST:event_areaCodeFieldFocusLost

    private void numberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFieldFocusGained
        if (numberField.isEditable()) {
            phoneNumberError.setText("");
            createButton.setEnabled(true);
        }
        numberField.setBackground(Color.white);
    }//GEN-LAST:event_numberFieldFocusGained

    private void numberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFieldFocusLost
        boolean validationResult = formValidator.verifyStringInput(numberField.getText());
        if (validationResult) {
            if (formValidator.verifyPhoneNumber(numberField.getText())) {
                if ((phoneNumberError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        phoneNumberError.setText("Please Enter  a valid 7-digit Number");
        numberField.setBackground(Color.pink);
        errorCount++;
        createButton.setEnabled(false);
    }//GEN-LAST:event_numberFieldFocusLost

    private void numberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if(null != cityCombo.getSelectedItem()){
            City city = (City) cityCombo.getSelectedItem();
            if(null != areaCombo.getSelectedItem()){
                Area area = (Area) areaCombo.getSelectedItem();
                Citizen citizen = area.getCitizenDirectory().addCitizen();
                citizen.getPerson().setFirstName(firstNameField.getText());
                citizen.getPerson().setLastName(lastNameField.getText());
                 DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                  dateFormat.setLenient(false);
                 Date date = null;
                  try {
                    date = dateFormat.parse(dobField.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisterCitizenJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                citizen.getPerson().setDateOfBirth(date);
                citizen.setEmailId(emailField.getText());
                citizen.setPhoneNumber(areaCodeField.getText()+numberField.getText());
                citizen.setResidence((House)aptCombo.getSelectedItem());
                citizen.getResidence().getResidents().add(citizen);
                JOptionPane.showMessageDialog(null, "Step 1 done! You will be redirected to next page");
                RegisterMedicalRecordJPanel registerMedicalRecordJPanel = new RegisterMedicalRecordJPanel(userPanel,area, citizen);
        userPanel.add("registerMedicalRecordJPanel", registerMedicalRecordJPanel);
        CardLayout layout = (CardLayout) userPanel.getLayout();
        layout.next(userPanel);
                
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void dobFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobFieldFocusGained
        if (dobField.getText() != null && (dobField.getText().equals("mm/dd/yyyy"))) {
            dobField.setText("");
        }
        dobError.setText("");
        dobField.setBackground(Color.white);
        if (errorCount == 0) {
            createButton.setEnabled(true);
        }
    }//GEN-LAST:event_dobFieldFocusGained

    private void dobFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobFieldFocusLost
        boolean validationResult = formValidator.verifyStringInput(dobField.getText());
        if (validationResult) {
            if (formValidator.verifyDateFormat(dobField.getText(), "MM/dd/yyyy")) {
                if ((dobError.equals(""))) {
                    errorCount--;
                }
                return;
            }
        }
        dobError.setText("Please Enter  a valid dob in mm/dd/yyyy format");
        dobField.setBackground(Color.pink);
        createButton.setEnabled(false);
    }//GEN-LAST:event_dobFieldFocusLost

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobFieldActionPerformed

    private void areaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboActionPerformed
        if (null != areaCombo.getSelectedItem()) {
            Area area = (Area) areaCombo.getSelectedItem();
            if (null != area) {
                streetCombo.removeAllItems();
                for (Street street : area.getStreetMap().getStreetList()) {
                    streetCombo.addItem(street);
                }
            }
    }//GEN-LAST:event_areaComboActionPerformed
    }
    private void streetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetComboActionPerformed
        if (null != streetCombo.getSelectedItem()) {
            Street street = (Street) streetCombo.getSelectedItem();
            if (null != street) {
                plotCombo.removeAllItems();
                for (Plot plot : street.getPlotList()) {
                    plotCombo.addItem(plot);
                }
            }
        }
    }//GEN-LAST:event_streetComboActionPerformed

    private void plotComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotComboActionPerformed
        if (null != plotCombo.getSelectedItem()) {
            Plot plot = (Plot) plotCombo.getSelectedItem();
            if (null != plot) {
                aptCombo.removeAllItems();
                for (House house : plot.getApartmentMap()) {
                    aptCombo.addItem(house);
                }
            }
        }
    }//GEN-LAST:event_plotComboActionPerformed

    private void aptComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptComboActionPerformed
        if (null != aptCombo.getSelectedItem()) {
            House house = (House) aptCombo.getSelectedItem();
            if (null != house) {
                if (errorCount == 0) {
                    createButton.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_aptComboActionPerformed

    private void cityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboActionPerformed
        if (null != cityCombo.getSelectedItem()) {
            City city = (City) cityCombo.getSelectedItem();
            if (null != city) {
                areaCombo.removeAllItems();
                for (Area area : city.getAreaDirectory().getAreaList()) {
                    areaCombo.addItem(area);
                }
            }
        }
    }//GEN-LAST:event_cityComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aptCombo;
    private javax.swing.JTextField areaCodeField;
    private javax.swing.JComboBox areaCombo;
    private javax.swing.JComboBox cityCombo;
    private javax.swing.JLabel commonErrorLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel dobError;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel emailAddressError;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel firstNameError;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameError;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel middleNameError;
    private javax.swing.JTextField numberField;
    private javax.swing.JLabel occupationError;
    private javax.swing.JLabel phoneNumberError;
    private javax.swing.JComboBox plotCombo;
    private javax.swing.JLabel stAddressError;
    private javax.swing.JComboBox streetCombo;
    private javax.swing.JLabel townError;
    private javax.swing.JLabel zipError;
    // End of variables declaration//GEN-END:variables
}
